//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ta_blog
    {
        public long blogid { get; set; }
        public string blogtitle { get; set; }
        public string blogdescription { get; set; }
        public string blogimage { get; set; }
        public System.DateTime blogdate { get; set; }
        public System.DateTime blogupdate { get; set; }
        public string blogkeywords { get; set; }
        public string blogtags { get; set; }
        public string blogwebsite { get; set; }
        public bool blogpublished { get; set; }
    }
}
