//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ta_Manager
    {
        public long mid { get; set; }
        public string mguid { get; set; }
        public string mcontent { get; set; }
        public string mrowtype { get; set; }
    }
}
