//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ta_ussbk_client_comment
    {
        public long cmntid { get; set; }
        public string cmntype { get; set; }
        public string cmntcontent { get; set; }
        public Nullable<System.DateTime> cmntdate { get; set; }
        public Nullable<System.DateTime> cmntcreatedate { get; set; }
        public Nullable<long> userfkid { get; set; }
    }
}
