//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ta_ussbk_clientrecord
    {
        public int recordid { get; set; }
        public string productname { get; set; }
        public string productid { get; set; }
        public string businessname { get; set; }
        public string clientname { get; set; }
        public string clientemail { get; set; }
        public string contactmobile { get; set; }
        public string clientaddress { get; set; }
        public string formodule { get; set; }
        public string userrole { get; set; }
        public Nullable<bool> userblocked { get; set; }
        public Nullable<System.DateTime> expirydate { get; set; }
        public string upassword { get; set; }
        public string remarks { get; set; }
    }
}
