//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ta_ussbk_categoryMaster
    {
        public ta_ussbk_categoryMaster()
        {
            this.ta_ussbk_Description = new HashSet<ta_ussbk_Description>();
        }
    
        public int catid { get; set; }
        public string catname { get; set; }
    
        public virtual ICollection<ta_ussbk_Description> ta_ussbk_Description { get; set; }
    }
}
