//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TA_ussbk_Coupons
    {
        public int couponid { get; set; }
        public string couponcode { get; set; }
        public string cmsgforuser { get; set; }
        public string cAdminRemarks { get; set; }
        public Nullable<bool> cblocked { get; set; }
        public Nullable<int> camount { get; set; }
    }
}
