//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ta_ussbk_Description
    {
        public int descriptionid { get; set; }
        public Nullable<int> desctitile { get; set; }
        public Nullable<int> desccategory { get; set; }
        public string descvideolink { get; set; }
        public string websitemodule { get; set; }
        public string descanydescription { get; set; }
    
        public virtual ta_ussbk_categoryMaster ta_ussbk_categoryMaster { get; set; }
        public virtual ta_ussbk_TitleMaster ta_ussbk_TitleMaster { get; set; }
    }
}
