//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ussdbEntities : DbContext
    {
        public ussdbEntities()
            : base("name=ussdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ta_ussbk_categoryMaster> ta_ussbk_categoryMaster { get; set; }
        public DbSet<ta_ussbk_clientrecord> ta_ussbk_clientrecord { get; set; }
        public DbSet<ta_ussbk_Description> ta_ussbk_Description { get; set; }
        public DbSet<ta_ussbk_TitleMaster> ta_ussbk_TitleMaster { get; set; }
        public DbSet<TA_ussbk_Coupons> TA_ussbk_Coupons { get; set; }
        public DbSet<Ta_Manager> Ta_Manager { get; set; }
        public DbSet<ta_ussbk_ProjectDetail> ta_ussbk_ProjectDetail { get; set; }
        public DbSet<ta_blog> ta_blog { get; set; }
        public DbSet<ta_blog_tags> ta_blog_tags { get; set; }
        public DbSet<ta_ussbk_client_comment> ta_ussbk_client_comment { get; set; }
    }
}
